services:
  api:
    image: ghcr.io/gmelvyn/rrb/api:${API_TAG}
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:4500"
    env_file:
      - .env

  front:
    image: ghcr.io/gmelvyn/rrb/front:${FRONT_TAG}
    container_name: front
    restart: unless-stopped
    ports:
      - "80:4600"
